/* eslint-disable */
// GENERATED by scripts/build-content.mjs — do not edit. Run `npm run build:content`.
import type { ContentMeta } from './registry'

export interface ManifestEntry {
  collection: string
  slug: string
  path: string
  meta: ContentMeta
}

export const manifest: ManifestEntry[] = [
  {
    "collection": "compare",
    "slug": "jobber-alternative-cleaning",
    "path": "/compare/jobber-alternative-cleaning",
    "meta": {
      "title": "A Jobber alternative built for cleaning businesses",
      "description": "Jobber is built for trades. CleanDock is built for cleaning businesses — recurring cleans, online booking, before/after photos, and 5 users for $49.99/mo. An honest pricing and feature comparison.",
      "summary": "Jobber is good software that wasn't built for cleaning. Here's an honest comparison of what each costs and where each one actually fits.",
      "updated": "2026-07-27",
      "targetQuery": "jobber alternative for cleaning business"
    }
  }
]
