/**
 * Generates the marketing-content manifest and the sitemap from src/content/.
 *
 * Runs before every build and before `npm run dev` (see the `prebuild` / `predev` scripts).
 * Two outputs:
 *
 *   src/features/content/manifest.generated.ts  — frontmatter only, no article bodies
 *   public/sitemap.xml                          — static routes + every published article
 *
 * The manifest matters for bundle size. Reading frontmatter with an eager `import.meta.glob`
 * puts each MDX file in the static import graph, which stops Rollup from code-splitting the
 * lazy import — every article ends up in the main bundle. Generating the metadata separately
 * keeps the article bodies purely dynamic, one chunk each.
 *
 * Both outputs are committed so a plain `vite build` works even if this hasn't been re-run.
 * Collection config and the file scan live in scripts/lib/content.mjs, shared with the
 * prerender step.
 */
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { ROOT, SITE_URL, STATIC_ROUTES, collectEntries } from './lib/content.mjs'

function writeManifest(entries) {
  const body = `/* eslint-disable */
// GENERATED by scripts/build-content.mjs — do not edit. Run \`npm run build:content\`.
import type { ContentMeta } from './registry'

export interface ManifestEntry {
  collection: string
  slug: string
  path: string
  meta: ContentMeta
}

export const manifest: ManifestEntry[] = ${JSON.stringify(entries, null, 2)}
`
  writeFileSync(join(ROOT, 'src', 'features', 'content', 'manifest.generated.ts'), body, 'utf8')
}

function writeSitemap(entries) {
  const published = entries.filter((e) => !e.meta.draft)
  const today = new Date().toISOString().slice(0, 10)

  const urls = [
    ...STATIC_ROUTES.map((r) => ({ loc: r.path, lastmod: today, ...r })),
    ...published.map((e) => ({
      loc: e.path,
      lastmod: e.meta.updated,
      changefreq: 'monthly',
      priority: '0.8',
    })),
  ]

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!--
  GENERATED by scripts/build-content.mjs — do not edit by hand.
  Articles come from src/content/; everything else from STATIC_ROUTES in scripts/lib/content.mjs.
  Excluded deliberately: /auth/register (redirect), /auth/tester and /billing/* (noindex),
  and /app/* /book/* /public/* /s/* (robots.txt Disallow).
-->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls
  .map(
    (u) => `  <url>
    <loc>${SITE_URL}${u.loc}</loc>
    <lastmod>${u.lastmod}</lastmod>
    <changefreq>${u.changefreq}</changefreq>
    <priority>${u.priority}</priority>
  </url>`
  )
  .join('\n')}
</urlset>
`
  writeFileSync(join(ROOT, 'public', 'sitemap.xml'), xml, 'utf8')
  return urls.length
}

let entries
try {
  entries = collectEntries()
} catch (err) {
  console.error(`\n[content] ${err.message}\n`)
  process.exit(1)
}

writeManifest(entries)
const urlCount = writeSitemap(entries)

const drafts = entries.filter((e) => e.meta.draft).length
console.log(
  `[content] ${entries.length - drafts} published, ${drafts} draft; sitemap has ${urlCount} URLs`
)
